label: Counter
icon: speed
description: "Animated counter for highlighting key stats or figures."
structures:
  - containerSections
  - cardSections
  - splitSections
  - gridItemSections
  - accordionSections
  - carouselSections
  - contentSelectorSections
value:
  _component: building-blocks/core-elements/counter
  number: 100
  prefix: "$"
  suffix: "USD"
  alignX: start
preview:
  text:
    - Counter
  subtext:
    - template: "{prefix}{number}{suffix}"
picker_preview:
  text: Counter
  subtext: "Animated counter for highlighting key stats or figures."
  icon: speed

_inputs:
  number:
    type: number
    comment: The number to count to.
  prefix:
    comment: Text immediately before the number.
  suffix:
    comment: Text immediately after the number.
  alignX:
    comment: The horizontal alignment of the counter.
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
