label: Definition List
icon: dns
description: "Lists term/definition pairs for structured content."
structures:
  - containerSections
  - cardSections
  - splitSections
  - gridItemSections
  - accordionSections
  - carouselSections
  - contentSelectorSections
value:
  _component: building-blocks/core-elements/definition-list
  items: []
  alignX: start
preview:
  text:
    - Definition List
picker_preview:
  text: Definition List
  subtext: "Lists term/definition pairs for structured content."
  icon: dns

_inputs:
  items:
    type: array
    label: List Items
    options:
      structures: _structures.definitionListItems
  alignX:
    type: select
    comment: The horizontal alignment of the definition list items.
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End

_structures:
  definitionListItems:
    values:
      - label: Definition List Item
        value:
          title: ""
          text: ""
        preview:
          icon: list
          text:
            - key: title
            - Definition List Item
          subtext:
            - key: text
        _inputs:
          title:
            type: text
            comment: A bolded title for the list item.
          text:
            type: textarea
            comment: The text content of the list item.
