label: Embed
icon: data_object
description: "Responsive wrapper for third-party embeds."
structures:
  - containerSections
  - cardSections
  - splitSections
  - gridItemSections
  - accordionSections
  - carouselSections
  - contentSelectorSections
value:
  _component: building-blocks/core-elements/embed
  source: ""
  title: ""
  aspectRatio: landscape
preview:
  text:
    - Embed
  subtext:
    - key: title
picker_preview:
  text: Embed
  subtext: "Responsive wrapper for third-party embeds."
  icon: data_object

_inputs:
  source:
    type: url
    comment: The url source for the iframe.
    options:
      disable_upload_file: true
      disable_direct_input: false
      disable_upload_file_in_file_browser: true
      hide_link_to_file: true
      hide_link_to_page: false
      hide_link_to_email_address: true
      hide_link_to_telephone: true
  aspectRatio:
    type: select
    comment: The aspect ratio of the embed.
    options:
      values:
        - id: square
          name: Square (1:1)
        - id: landscape
          name: Landscape (4:3)
        - id: portrait
          name: Portrait (3:4)
        - id: widescreen
          name: Widescreen (16:9)
