label: Form
icon: checklist_rtl
description: "Groups form fields into one submission area."
structures:
  - containerSections
  - cardSections
  - splitSections
  - gridItemSections
  - accordionSections
  - carouselSections
  - contentSelectorSections
value:
  _component: building-blocks/forms/form
  action: "./"
  formBlocks: []
preview:
  text:
    - Form
  subtext:
    - key: label
picker_preview:
  text: Form
  subtext: "Groups form fields into one submission area."
  icon: checklist_rtl
_inputs:
  action:
    type: url
    comment: Where to send the form-data when the form is submitted. The URL that processes the form submission.
  formBlocks:
    type: array
    comment: The form blocks to render inside the form.
    options:
      structures: _structures.formBlocks
