label: Spacer
icon: space_bar
description: "Adds adjustable spacing between content sections."
structures:
  - containerSections
  - cardSections
  - splitSections
  - gridItemSections
  - accordionSections
  - carouselSections
  - contentSelectorSections
value:
  _component: building-blocks/core-elements/spacer
  size: md
preview:
  text:
    - Spacer
  subtext:
    - key: size
picker_preview:
  text: Spacer
  subtext: "Adds adjustable spacing between content sections."
  icon: space_bar

_inputs:
  size:
    type: select
    comment: The amount of space to add.
    options:
      values:
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xl
        - id: 3xl
          name: 3xl
