label: Divider
icon: horizontal_rule
description: "Visual separator for dividing content sections."
structures:
  - containerSections
  - cardSections
  - splitSections
  - gridItemSections
  - accordionSections
  - carouselSections
  - contentSelectorSections
value:
  _component: building-blocks/core-elements/divider
  paddingVertical: "lg"
preview:
  text:
    - Divider
picker_preview:
  text: Divider
  subtext: "Visual separator for dividing content sections."
  icon: horizontal_rule

_inputs:
  paddingVertical:
    comment: The space on the top and bottom of the horizontal line.
    type: select
    options:
      values:
        - id: none
          name: None
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xl
        - id: 3xl
          name: 3xl
